### ISSUE TITLE
Setup development environment

### ISSUE THREAD

**Issue by anbraten** [project-leek/project-leek#14]
Every developer should setup her / his own local development environment.

**Comment by anbraten** [comment]
## Editor
VS-Code?

## VS-Code Plugins: 

- ESLint
- Vetur
- Vue Peek
- Tailwind CSS IntelliSense
- Live Share (optional)

## Other tools
- docker
- node.js

## Windows users
It is recommended to work in WSL with Ubuntu to properly use docker and node-js.
Follow the basics of this tutorial: https://code.visualstudio.com/docs/remote/wsl-tutorial

Install node.js and docker in WSL.

Inside WSL you can run `code .` to open VS-Code

**Comment by anbraten** [comment]
@schnickalodeon Please set to done if it works for you as well 🤣

**Comment by schnickalodeon** [comment]
Works for me
