### ISSUE TITLE
Create a Flow to see all Tags

### ISSUE THREAD

**Issue by julianhahn** [project-leek/project-leek#144]
- [x] add a short comprehensive flow on lucidchart (copy the link as an comment)
- [x] search for a completed design and copy an image or link to the issue
  - see spotify discover page
- [x] integrate your flow into FIGMA for our own purposes and paste a link as comment

**Comment by JanEberlein** [comment]
Nice idea 😄 
I tweaked the colors and borders a bit and removed the small details from the collapsed groups. They weren't readable and not really necessary
