### ISSUE TITLE
Create a Flow to create new Tag

### ISSUE THREAD

**Issue by julianhahn** [project-leek/project-leek#146]
- [x] add a short comprehensive flow on lucidchart (copy the link as an comment)
- [x] search for a completed design and copy an image or link to the issue
- [x] integrate your flow into FIGMA for our own purposes and paste a link as comment

**Comment by julianhahn** [comment]
Add a new Tag (Desktop) https://i.imgur.com/YVupVxD.png

**Comment by schnickalodeon** [comment]
> Add a new Tag (Desktop) https://i.imgur.com/YVupVxD.png

Can we use for Desktop-View later (mobile first)

**Comment by julianhahn** [comment]
https://dribbble.com/shots/2253998/attachments/2253998-Spotify-Persistent-Search?mode=media
As a simple reference to the spotify-search. We have to recreate this later
