### ISSUE TITLE
create a Flow to delete a Tag

### ISSUE THREAD

**Issue by julianhahn** [project-leek/project-leek#148]
- [x] add a short comprehensive flow on lucidchart (copy the link as an comment)
- [x] ~~search for a completed design and copy an image or link to the issue~~
- [x] integrate your flow into FIGMA for our own purposes and paste a link as comment

**Comment by JanEberlein** [comment]
https://www.figma.com/file/RevVhXP9iyGxmch31H0Tce/SMP-UI?node-id=0%3A1

**Comment by julianhahn** [comment]
After I click on the settings button, the settings menu won't go away. I can't use the mockup further after the interaction with your element. Please fix that.

**Comment by JanEberlein** [comment]
Its fixed. There is an option 'close when clicking outside' when editing the interactions of the element that is opening the overlay

**Comment by schnickalodeon** [comment]
It would be nice, if the user gets feedback when a tag was deleted (You can use our Headquarters-Tag if you want)

**Comment by JanEberlein** [comment]
good idea 👍
