### ISSUE TITLE
Create a Flow for connecting and first setup of the box

### ISSUE THREAD

**Issue by julianhahn** [project-leek/project-leek#150]
- [x] add a short comprehensive flow on lucidchart (copy the link as an comment)
- [x] ~search for a completed design and copy an image or link to the issue~
- [x]  ~integrate your flow into FIGMA for our own purposes and paste a link as comment~

**Comment by schnickalodeon** [comment]
@tcoro where can I see your changes. Can't find something on figma?

**Comment by schnickalodeon** [comment]
Add a short comprehensive flow:
![image](https://user-images.githubusercontent.com/45515005/103304098-03dde680-4a08-11eb-8e66-d189d17c6ff7.png) ?

**Comment by tcoro** [comment]
> @tcoro where can I see your changes. Can't find something on figma?

the setup wizard is from [comitup](https://github.com/davesteele/comitup).
We agreed on not changing anything on comitup since it might break it

**Comment by schnickalodeon** [comment]
Ok, then it is documented now :) 

> > @tcoro where can I see your changes. Can't find something on figma?
> 
> the setup wizard is from [comitup](https://github.com/davesteele/comitup).
> We agreed on not changing anything on comitup since it might break it, hence why there is no custom design on figma for that
