### ISSUE TITLE
Milestone Presentation

### ISSUE THREAD

**Issue by tcoro** [project-leek/project-leek#157]
https://docs.google.com/presentation/d/1aZuNXzPhY9reFOoV_YbyX2JSZpLXdIUJgI9nq5opc8c/edit?usp=sharing

**Comment by tcoro** [comment]
# Missing:
- How to create groups?
- How to choose selected speaker?
- What is a song, playlist, artist radio, etc?

# First Box Setup Idea
- Box is shipped with own wlan with standart credentials
- Connect with that wlan
- Box shippes setup frontned for private wlan
- If succesful, box shippes now intended frontend

# Other:
- Youtube is not important yet, but:
- Dont forget to be modular
- Error handling not needed yet
 - if wanted, simple log interface with stamp is okay
 - display on box is too expensive, if visual aid needed, simple red led is enough

**Comment by schnickalodeon** [comment]
Approved 👍
