### ISSUE TITLE
Create Flows for managing groups

### ISSUE THREAD

**Issue by JanEberlein** [project-leek/project-leek#168]
groups need to be:
- [x] created
- [x] edited
- [x] deleted

**Comment by schnickalodeon** [comment]
1. Lucidchart-Flow

![image](https://user-images.githubusercontent.com/45515005/103304475-0725a200-4a09-11eb-8a69-3e3997d243ad.png)

**Comment by schnickalodeon** [comment]
@tcoro Does a design already exist?

**Comment by tcoro** [comment]
> @tcoro Does a design already exist?

not yet, but the design should be similiar to the details view of a tag (v2).
will do that later

**Comment by schnickalodeon** [comment]
So you want us to review this?:

> 1. [Lucidchart-Flow](https://lucid.app/lucidchart/invitations/accept/d437bae7-a5d4-406b-8958-0d041b7ce651)
> 
> ![image](https://user-images.githubusercontent.com/45515005/103304475-0725a200-4a09-11eb-8a69-3e3997d243ad.png)

**Comment by tcoro** [comment]
it was my first idea, but I have new one, will work on that

**Comment by tcoro** [comment]
this is the other idea.
Basically, the first one was in mind with an extra "Group Detail" screen similiar to the "Tag Details", but this does not need it and works with the v3 design (just collapsing and elapsing groups)

![image](https://user-images.githubusercontent.com/9517685/103310239-67bbdb80-4a17-11eb-80e7-56a90fa29ac8.png)
