### ISSUE TITLE
Create a general Button Component

### ISSUE THREAD

**Issue by julianhahn** [project-leek/project-leek#175]
- option / property to open links (`:to`)
- property to support lazy mode (async click events) with a spinner animation indicating something is happening and disable it while loading
- option to make the button a back link

**Comment by anbraten** [comment]
Sample code for the `doClick` handler

```ts
async doClick(): Promise<void> {
    if (this.disabled) {
      return;
    }

    if (this.withLoading) {
      this.isLoading = true;
      const asyncFunction = this.$listeners['click'] as () => Promise<void>;
      await asyncFunction();
      this.isLoading = false;
    } else {
      this.$emit('click');
    }

    if (this.to) {
      void this.$router.push(this.to);
      return;
    }

    if (this.back) {
      this.$router.go(-1);
    }
  }
```

**Comment by schnickalodeon** [comment]
I will ignore the With loading functionality for the moment. 

Maybe we will implement that later

**Comment by JanEberlein** [comment]
> `const asyncFunction = this.$listeners['click'] as () => Promise<void>;`

this can't work since `$listeners` were removed in vue 3.x (see [vue docs](https://v3.vuejs.org/guide/migration/listeners-removed.html))
