### ISSUE TITLE
can't login with spotify

### ISSUE THREAD

**Issue by JanEberlein** [project-leek/project-leek#216]
Every time I try to login with spotify I encounter the following errror code:
INVALID_CLIENT: Invalid client

![image](https://user-images.githubusercontent.com/37227462/103477626-02723c80-4dc1-11eb-9941-0c5233b96ac0.png)

This happens both on Firefox and Chrome as well as in incognito-mode

The URL is always: https://accounts.spotify.com/authorize?client_id=SPOTIFY_CLIENT_ID&response_type=code&redirect_uri=http%3A%2F%2Flocalhost%3A3030%2Foauth%2Fspotify%2Fcallback&scope=user-read-email%20user-read-private%20user-read-playback-state%20user-modify-playback-state%20user-read-currently-playing%20user-read-recently-played

**Comment by anbraten** [comment]
@JanEberlein You have to correctly create your `.env` file?

accounts.spotify.com/authorize?client_id=**SPOTIFY_CLIENT_ID**&response_type=code&redirect_uri=http%3A%2F%2Flocalhost%3A3030%2Foauth%2Fspotify%2Fcallback&scope=user-read-email%20user-read-private%20user-read-playback-state%20user-modify-playback-state%20user-read-currently-playing%20user-read-recently-played

Please be careful with posting urls. This one is fine, but do not post the correct `client-id`

**Comment by JanEberlein** [comment]
I literally have no idea what you just told/asked me.

**Comment by anbraten** [comment]
I updated the readme. [This](https://github.com/project-leek/project-leek#edit-config) part should help. For our specific config check `Discord -> documents`.
