### ISSUE TITLE
Update Figma Mockup

### ISSUE THREAD

**Issue by schnickalodeon** [project-leek/project-leek#281]
- Edit Screen
  - create edit button 
  - create delete button
- Settings Screen
  - create selecte speaker option
  - create logout button

**Comment by tcoro** [comment]
![image](https://user-images.githubusercontent.com/9517685/105686788-f11bdc00-5ef7-11eb-8c5b-9d5edd5994c9.png)

![image](https://user-images.githubusercontent.com/9517685/105686811-faa54400-5ef7-11eb-8f91-59ab8377f113.png)
