### ISSUE TITLE
improve UI based on designers feedback (Julian got the notes)

### ISSUE THREAD

**Issue by tcoro** [project-leek/project-leek#310]

**Comment by julianhahn** [comment]
I'll leave the suggestions here

**Comment by julianhahn** [comment]
![image](https://user-images.githubusercontent.com/40185075/106056217-bcbe4080-60ee-11eb-82aa-25b35b0ce46d.png)

![image](https://user-images.githubusercontent.com/40185075/106056280-cb0c5c80-60ee-11eb-820f-6689eac9cae3.png)

**Comment by tcoro** [comment]
fixed in and closed by https://github.com/project-leek/project-leek/pull/321
