### ISSUE TITLE
fix bug in edit track view (see video)

### ISSUE THREAD

**Issue by schnickalodeon** [project-leek/project-leek#323]
Error at Edit the Track in the Edit Tag screen:

![error](https://user-images.githubusercontent.com/45515005/106003860-e78aa380-60b2-11eb-8fa4-107ce18dd4d0.gif)

**Comment by schnickalodeon** [comment]
![image](https://user-images.githubusercontent.com/45515005/106003428-7cd96800-60b2-11eb-99b7-40a8fa08c11a.png)

**Comment by JanEberlein** [comment]
This was addressed as part of PR #224
