### ISSUE TITLE
projekt management

### ISSUE THREAD

**Issue by JanEberlein** [project-leek/project-leek#349]
ticket pool in github, gemeinsame Absprache (im team und mit Kunden) was in den aktuellen Milestone kommen soll, alles zentral, 3x daily standup, gemeinsamer google calendar, gemeinsamer Discord Server (für spontaneres und informelleres gemeinsames Arbeiten), interne team evaluation und regelmäßiges feedback

**Comment by tcoro** [comment]
dont forget this:
https://github.com/project-leek/project-leek/issues/233

closes https://github.com/project-leek/project-leek/issues/233
