### ISSUE TITLE
feasibility study / define practicability of system design

### ISSUE THREAD

**Issue by schnickalodeon** [project-leek/project-leek#35]
Pi: 
- run docker
- serve public ui
- access nfc reader

Ui: 
- accounts via OAuth and spotify (later youtube, etc?) 
- recognise same User login in with different services
- load playlist artwork
- upload own images for nfc tags
- access spotify connected speakers and be able to select one
    - be able to save one as standart
- if ui in cloud, be able to select which box you want to log in
     - make api to change data on that box

Other: 
- make a 3d print version

**Comment by tcoro** [comment]
add client requirements (f.e. cost)
