### ISSUE TITLE
Create a concept of the system design / components 

### ISSUE THREAD

**Issue by anbraten** [project-leek/project-leek#4]
Create a sketch of the components for the box

**Comment by anbraten** [comment]
![photo_2020-10-28_18-38-51](https://user-images.githubusercontent.com/6918444/97475208-3e1a0180-194d-11eb-9f52-c1b6f400e308.jpg)

**Comment by schnickalodeon** [comment]
https://lucid.app/invitations/accept/abe6f48a-ea07-4c2d-982b-d1f954b6344f
