### ISSUE TITLE
remove hello-worlds from code

### ISSUE THREAD

**Issue by anbraten** [project-leek/project-leek#91]
remove all hello-worlds from the code:
 - npm dependencies
 - services
 - components
 - commons types

**Comment by julianhahn** [comment]
@anbraten could you check out my latest push? After yarn reset and yarn build my branch won't start on yarn start but did not gave me any error messages. Just frezees on yarn start.
Thx

**Comment by anbraten** [comment]
@julianhahn Could you create a draft PR so I can check there?
